class DomainError(Exception): ...


class CreateError(DomainError): ...


class NotFoundError(DomainError): ...


class WidgetNotFoundError(NotFoundError): ...


class DonateNotFoundError(NotFoundError): ...
